language: python

python:
    - "pypy"
    - "2.7"
    - "3.5"
    - "3.6"

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=docs
      install: pip install tox
      script: tox -e $TOX_ENV

install:
    - travis_retry pip install -e .
    - travis_retry pip install -q codecov

script: python setup.py nosetests

after_success: codecov

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#inboxen"
        use_notice: true

sudo: false
